[package]
name = "kaleidoscope-tutorial"
version = "0.1.0"
edition = "2021"

[dependencies]
lalrpop-util = { git = "https://github.com/Michael-F-Bryan/lalrpop", features = ["lexer"], branch = "custom-lexer" }

