[package]
name = "kaleidoscope-tutorial"
version = "0.1.0"
edition = "2021"

[dependencies]
codespan = "0.11.1"
lalrpop-util = { git = "https://github.com/Michael-F-Bryan/lalrpop", features = ["lexer"], branch = "custom-lexer" }

[build-dependencies]
lalrpop = "0.20.0"

